### ISSUE TITLE
Upstream Xblock Aside commits

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#100]
As outlined at https://github.com/mitodl/rapid-response-xblock#rapid-response-xblock we need to upstream the following commits to edx-platform:

    https://github.com/mitodl/edx-platform/commit/b26db017a55140bb7940c3fbfac5b4f27128bffd
    https://github.com/mitodl/edx-platform/commit/96578f832d786d90162c555f1cfa08f69ba294d2
    https://github.com/mitodl/edx-platform/commit/1bd36be3b31210faa8af09fc28ff4a885807e20e

If it's easier, these can be combined in one PR. Or it may be best to keep the studio changes separate from the lms changes. 

If there is any refactoring or test-writing involved, George or Gavin should review before we seek an edX reviewer.

**Comment by amir-qayyum-khan** [comment]
@pdpinch 
they are link together
thats why i cannot make one PR for cms and one for lms
but we can make one PR for 3 commits or 3 PRs for each commit

**Comment by pdpinch** [comment]
@tasawernawaz In his [most recent comment](https://app.zenhub.com/workspaces/edx-platform-5666e4681bd9a6596812e8e7/issues/edx/edx-platform/19089#issuecomment-443764469), Cale asked us to re-enable a xBlock aside test and see if we can get the PR working with it.

**Comment by pdpinch** [comment]
This has been merged upstream at edX!
