### ISSUE TITLE
Make the enabling of instructor email configurable

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#105]
See https://openedx.atlassian.net/browse/CRI-132

As an instructor, I find it confusing when a new course is created for me and I can't email my learners.

As an open edX support staff, I find it time-consuming and a distraction to have to turn on instructor emails for each course individually through the django admin.

It would be better if the the default setting for `email_enabled` were configurable by a site setting instead of hard-coded to default to False.

See https://github.com/edx/edx-platform/blob/open-release/hawthorn.2/lms/djangoapps/bulk_email/models.py#L418

Also, this conversation in Slack: https://openedx.slack.com/archives/C12M8M5AR/p1541014528004600

**Comment by pdpinch** [comment]
blocked until we resolve feedback from edX on https://openedx.atlassian.net/browse/CRI-132

**Comment by pdpinch** [comment]
Ok, I'm convinced that Marco's recommended solution is the same as what I wrote in the description. 

1. Add a setting to the configuration repo called `COURSE_EMAIL_ENABLED_DEFAULT`
2. Use that configuration setting  to set the default value of `CourseAuthorization.email_enabled`

It would be nice to write a one-time migration script for us too.

**Comment by pdpinch** [comment]
(asking the same question, but this time in the right place)

@NotoriousMKD tells me that the django-admin setting worked on the next release.

Do you want to turn it on in production now, and then we can call it a day? Since this is a database setting, I don't think it will travel from our QA stack to our production stack. You'll need to turn it on in production -- it's up to you whether to do it now or later.

**Comment by NotoriousMKD** [comment]
@pdpinch it's turned on now, thanks!
