### ISSUE TITLE
cherry-picks for "Improved Problem Response Report"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#109]
See the following PRs:

https://github.com/edx/edx-platform/pull/17698
https://github.com/edx/edx-platform/pull/17776
https://github.com/edx/edx-platform/pull/17824
https://github.com/edx/edx-platform/pull/17948
https://github.com/edx/edx-platform/pull/18170
https://github.com/edx/edx-platform/pull/18786

Note that some of these commits should already be included in mitod/hawthorn-release

**Comment by pdpinch** [comment]
@blarghmatey took a look at this. Most of the commits are already in our mitx/hawthorn-release branch but the ones that aren't have merge conflicts. 

It would be helpful to open a new PR the includes the remaining commits and an additional commit to resolve the conflicts.

**Comment by Ayub-Khan** [comment]
Created following pr for the issue [Pull Request](https://github.com/mitodl/edx-platform/pull/114)

**Comment by pdpinch** [comment]
@Ayub-Khan something went wrong with this. Maybe I specified the wrong cherry-picks, or maybe they were applied in the wrong order. 

Your PR #114 updated the UI correctly, but it also reverted the download format. From @NotoriousMKD:

> The navigation to get the problem or section you want to download data for is working, but the report has changed. You can see the difference in the two attached versions of the student state report. These reports come from the same block in the course but were generated on different days

> The first was generated on 12-12 and is the correct, updated version of the report that includes fields for `Answer`, `Answer ID`, `Correct Answer`, and `Question`.

[MITx_mkd.0001_2019_Spring_student_state_from_block-v1_MITx+mkd.0001+2019_Spring+type@problem+block@9f20ed8942be45a99689d307c5d48cef_2018-12-12-1607.xlsx](https://github.com/mitodl/edx-platform/files/2704299/MITx_mkd.0001_2019_Spring_student_state_from_block-v1_MITx%2Bmkd.0001%2B2019_Spring%2Btype.problem%2Bblock.9f20ed8942be45a99689d307c5d48cef_2018-12-12-1607.xlsx)

> The second is from 12-21, and does not include fields for `Answer`, `Answer ID`, `Correct Answer`, and `Question`.

[MITx_mkd.0001_2019_Spring_student_state_from_block-v1_MITx+mkd.0001+2019_Spring+type@problem+block@2baac4147ef54bcc8ab84c170672ac47_2018-12-21-1753.xlsx](https://github.com/mitodl/edx-platform/files/2704300/MITx_mkd.0001_2019_Spring_student_state_from_block-v1_MITx%2Bmkd.0001%2B2019_Spring%2Btype.problem%2Bblock.2baac4147ef54bcc8ab84c170672ac47_2018-12-21-1753.xlsx)

> They came from this course: https://mitx-qa-next.mitx.mit.edu/courses/course-v1:MITx+mkd.0001+2019_Spring/instructor#view-data_download

**Comment by Ayub-Khan** [comment]
@pdpinch ahh. It seems https://github.com/edx/edx-platform/pull/17948 updated the report generation code. I had no idea that we were using custom code for that. It seems edX people removed all the useless information from state field and moved "Answer","AnswerID", "Question" to state. Do we want to revert that and show them as separate fields ? Although we will have to add the Correct Answer field again as it was completely removed.

**Comment by pdpinch** [comment]
AFAIK, the current master behaves more like the [first condition](MITx_mkd.0001_2019_Spring_student_state_from_block-v1_MITx+mkd.0001+2019_Spring+type@problem+block@9f20ed8942be45a99689d307c5d48cef_2018-12-12-1607.xlsx) than the second, so I suspect I missed a commit in my cherry-pick list. I'm looking for it now.

**Comment by pdpinch** [comment]
I think this is the one we missed: https://github.com/edx/edx-platform/pull/18512

Also, if we don't have it already, we probably need https://github.com/edx/edx-platform/pull/18581

**Comment by Ayub-Khan** [comment]
@pdpinch I created this [pull request](https://github.com/mitodl/edx-platform/pull/117) with those cheery picks.

**Comment by pdpinch** [comment]
This can be closed when https://github.mit.edu/mitx/Spring-2019/issues/9 is closed

**Comment by pdpinch** [comment]
This has been deployed to production.
