### ISSUE TITLE
Change inputs in 'remote gradebook' instructor tab to select boxes

### ISSUE THREAD

**Issue by gsidebo** [mitodl/edx-platform#12]
Some parts of the legacy instructor dashboard from Dogwood were added back into the Ficus instructor dashboard and contained in a tab (https://github.com/mitocw/edx-platform/issues/74, https://github.com/mitocw/edx-platform/issues/76). These inputs for a section name and assignment name were originally simple text inputs, requiring that the user first click a button to spit out a list of valid options, then enter one of those options into the text box. This is time-consuming and user-un-friendly. These inputs should be changed to select boxes that have valid options populated from an API call.

![ss 2017-06-14 at 10 49 37](https://user-images.githubusercontent.com/14932219/27138784-504307fa-50ef-11e7-928a-39cddf1051b0.png)

**Comment by pdpinch** [comment]
@gsidebo this is done, right?

**Comment by gsidebo** [comment]
Yup, this is all set. Closing
