### ISSUE TITLE
Make default value of invite_only configurable

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/edx-platform#123]
We would like to make the default value of the `invitation_required` attribute of the courseware object configurable via a feature flag, to be named `COURSE_DEFAULT_INVITE_ONLY` 

As it is currently, this is a manually updated flag in the course advanced settings and we would like to be able to manage the default value across all courses in a given deployment. The default value of the added setting should remain the same as the current setting of `False`, but allow us to set it to `True` through the existing settings mechanism.

**Comment by tasawernawaz** [comment]
@pdpinch where this flag is defined 'invitation_required' ? Do we mean `Invitation Only` flag which is available in advance settings of course ?

**Comment by pdpinch** [comment]
Yes, that's it exactly.

**Comment by pdpinch** [comment]
@blarghmatey do you want that configurable through the django admin, or through a feature flag? 

If it's through the admin, is there an existing model you had in mind??

**Comment by blarghmatey** [comment]
My preference is to set it via either a feature flag, or at least some value in the `common.py` settings file which can be overridden using the `cms.env.json` file that is consumed through the `aws.py` settings file.

**Comment by pdpinch** [comment]
I updated the description -- we should choose the name for the flag.

**Comment by blarghmatey** [comment]
For the flag name I would imagine something like `COURSE_DEFAULT_INVITE_ONLY` would be fairly descriptive.
