### ISSUE TITLE
Chrome users get logged out

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#124]
This is a tracking issue for https://github.mit.edu/mitx/Spring-2019/issues/14

┆Issue is synchronized with this [Trello card](https://trello.com/c/zUVomsao) by [Unito](https://www.unito.io/learn-more)

**Comment by pdpinch** [comment]
Waiting on further testing from users

**Comment by blarghmatey** [comment]
We have determined that this is a result of a different MIT service setting an errant `csrftoken` cookie with a domain of `.mit.edu` which causes a conflict with our application for any POST requests. We have a temporary workaround but the next step is to investigate changes to the settings defined [here](https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L654-L656)

**Comment by blarghmatey** [comment]
@shaidar can you take a look at those settings and try modifying them on QA (current or next) and testing to see if it resolves our issue?

**Comment by pdpinch** [comment]
Can we just change the cookiename?

**Comment by markbreedlove** [comment]
I've tried to reproduce the issue by setting `csrftoken` cookies with higher-level domain names and different cookie options, to no avail. I think that @shaidar mentioned this before elsewhere, but it does not appear that there is an issue now with `csrftoken` -- or maybe that's not the only issue.

I will benefit from spending a little time with @shaidar, @blarghmatey, or someone else in the know, whenever you have a second, to see if I'm looking in the right place, and if the problem still exists.

**Comment by pdpinch** [comment]
IIRC, we ended up solving this by clearing the CSRF cookie value if any user visits us with it set. That will have the effect of logging them out of whatever service initially set the value, but that was a risk that site has been taking all along by setting the cookies at .mit.edu.
