### ISSUE TITLE
cherry-pick YouTube speed fixes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#129]
There were two.

I believe we want to have this ready to go for a 3/25 hot fix release.

**Comment by pdpinch** [comment]
@blarghmatey does this sound right?

**Comment by pdpinch** [comment]
@markbreedlove let me know if you have trouble finding the commits. At least one of them was discussed in the #video channel in Open EdX Slack.

**Comment by markbreedlove** [comment]
@pdpinch I'm looking at the following two. Do these look right?

`a85256e109 2019-01-23 rabiaiftikhar   EDUCATOR-3930 fix video player speed adjustments`
* https://github.com/edx/edx-platform/commit/a85256e10915803c25cf9a470de2d43603afd1de

`a5fe66863e 2019-02-27 DawoudSheraz   fix video player speed adjustments`
* https://github.com/edx/edx-platform/pull/19888/commits/a5fe66863eef403ffa4606a22c81ec2a367f1986

**Comment by markbreedlove** [comment]
@blarghmatey I should have flagged you on the comment above :arrow_up:

**Comment by markbreedlove** [comment]
I've cherry-picked the commits above into my local `mitx/hawthorn-release` and there are no conflicts. Assuming they're the right ones, are the next steps to push them up, and then close this issue? Anything else like a deployment?

**Comment by pdpinch** [comment]
Do we need this one also?  https://github.com/edx/edx-platform/pull/19708/commits/2ee631f66601f7db90eb48e13aa3931435bf9355

> I'm looking at the following two. Do these look right?
> a85256e109 2019-01-23 rabiaiftikhar EDUCATOR-3930 fix video player speed adjustments
> 
> edx@a85256e <https://github.com/edx/edx-platform/commit/a85256e10915803c25cf9a470de2d43603afd1de>
> a5fe66863e 2019-02-27 DawoudSheraz fix video player speed adjustments
> 
> edx@a5fe668 <https://github.com/edx/edx-platform/commit/a5fe66863eef403ffa4606a22c81ec2a367f1986>

**Comment by markbreedlove** [comment]
@pdpinch No, that's the same change as `a85256e1091`. I think someone must have done a `cherry-pick` or rebase or something that gave it a new commit ID. (The two commits I listed above are on the `master` branch of the upstream.)

**Comment by blarghmatey** [comment]
@markbreedlove there is indeed a build/deploy process which I can walk you through after planning.

**Comment by markbreedlove** [comment]
Made this fix to get deployment to work: https://github.com/mitodl/salt-ops/commit/340929c5a24d91b5660d475865565fa7909ccf85
