### ISSUE TITLE
Upstream "Added setting to manage from_email address"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#133]
https://github.com/mitodl/edx-platform/pull/113 adds a feature flag that sets an return address for all e-mail from the platform, instead of the current default of constructing an address for each course. See the PR description for more details. 

I had a preliminary conversation with edX and they seem inclined to merge this if we open a PR. 

The original PR doesn't have any tests. We will need to add tests, as well as annotations for the feature flag. 

┆Issue is synchronized with this [Trello card](https://trello.com/c/iWlIZpyb) by [Unito](https://www.unito.io/learn-more)

**Comment by blarghmatey** [comment]
Opened a PR https://github.com/edx/edx-platform/pull/20886

**Comment by ahmed-belal** [comment]
@pdpinch is this on the todo list for us? I tried looking at the PR @blarghmatey put up to be merged upstream but I can't seem to get details of the Jenkins job that failed. Any leads on what needs to be done would be greatly appreciated.

**Comment by pdpinch** [comment]
Yes it’s on the todo list. 

Tobias’s commit works in Ironwood, but it may not work in Juniper. And it needs tests before edX will accept it upstream. 

If you can’t get the job results, it’s probably because they’ve expired. You can push another commit to the branch to get a fresh test run, or it might be easier for you to open your own PR.

**Comment by asadiqbal08** [comment]
@pdpinch one question, so we do not need to be depended upon Juniper release for this ticket, I mean, master release would be sufficient to address this issue or we need to switch to juniper for fixing it ?

**Comment by pdpinch** [comment]
Please open the PR at edX against master.
