### ISSUE TITLE
Upstream “Added index on module_id column to eliminate full table scans”

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#134]
In PR #118 we restored a database index, the absence of which was causing serious performance issues. 

We don't know why edX removed this index. We'd like have this change upstream.

┆Issue is synchronized with this [Trello card](https://trello.com/c/nQHo2cTm) by [Unito](https://www.unito.io/learn-more)

**Comment by blarghmatey** [comment]
Opened a PR against upstream https://github.com/edx/edx-platform/pull/20885

**Comment by pdpinch** [comment]
@blarghmatey do we need this for Koa?

**Comment by blarghmatey** [comment]
No, the index is already in the database but it would still be good to get upstreamed to prevent regressions for people who are setting up a new database.

**Comment by shaidar** [comment]
@pdpinch Who should this be assigned to work on upstreaming?

**Comment by pdpinch** [comment]
Dave Ormsbee superseded this change with https://github.com/edx/edx-platform/pull/26617 which will be included in the lilac release.
