### ISSUE TITLE
Upstream "make default value of invite_only configurable"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#135]
In #123 / PR #126 we added a feature setting that sets the default value of the course setting `invite_only`. This avoids us having to set that flag for all courses on a server that is intended to be invite only for all courses. 

We would like to have this merged upstream into edx.org. I don't know if the PR has tests.

┆Issue is synchronized with this [Trello card](https://trello.com/c/bFw4F8UW) by [Unito](https://www.unito.io/learn-more)

**Comment by tasawernawaz** [comment]
Upstream PR: https://github.com/edx/edx-platform/pull/20596

**Comment by pdpinch** [comment]
@tasawernawaz looks like your PR never got reviewed, and now it needs a rebase. This isn't high priority, but I wanted to get it back on the todo list.

**Comment by tasawernawaz** [comment]
@pdpinch Pushed again after rebasing my PR.

**Comment by shaidar** [comment]
@pdpinch This didn't get upstreamed and guessing someone would need to be assigned to take it on again.

**Comment by pdpinch** [comment]
Thanks Sar. I thought I had left a note on this, but I guess not. 

This didn't work out the way I expected and I don't know right now if we want to continue using it. Is it turned on in courses-rc.xpro or courses.xpro?

**Comment by shaidar** [comment]
`COURSE_DEFAULT_INVITE_ONLY` is set to False on xpro RC and it's not set on production

**Comment by pdpinch** [comment]
I think we're using this on staging.mitx.mit.edu, to prevent not-staff users from accessing courses?
