### ISSUE TITLE
Re-implement overload and merge enrollment functionality from legacy dashboard

### ISSUE THREAD

**Issue by gsidebo** [mitodl/edx-platform#14]
Originally specified here: https://github.com/mitocw/edx-platform/issues/76

PR #10 re-implemented some legacy dashboard functionality that had to do with remote gradebook enrollment, but we held off on the "Overload/Merge enrollment list" features as we didn't yet know that we would need them. We've confirmed that they will still be useful, so this issue will cover the work to reintroduce those buttons and get them working

**Comment by pdpinch** [comment]
@blarghmatey @NotoriousMKD @gsidebo This can be closed, right?

**Comment by blarghmatey** [comment]
Yes
