### ISSUE TITLE
Create OVS uploader user and access token

### ISSUE THREAD

**Issue by gsidebo** [mitodl/edx-platform#142]
When we are ready to go live and give OVS users the ability to add HLS videos to edX, we will need an access token associated with an admin user. A new user should be created as a "master" OVS user, and should be given staff & superuser permissions. The access token can be added in Django admin at `/admin/oauth2/accesstoken/`. This access token value will be used in the request from OVS

**Comment by pdpinch** [comment]
@gsidebo @shaidar I think this is done?
