### ISSUE TITLE
edx-val transcript export failure

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/edx-platform#146]
When exporting a course that contains transcripts, there is a `ResourceNotFoundError` that occurs due to a hardcoded subdirectory in the export path that prevents the transcript file from being created. The specific location that causes the error is https://github.com/edx/edx-val/blob/master/edxval/api.py#L981

The first parameter to the `combine` call needs to be the `course_dir` path that is specified [here](https://github.com/edx/edx-platform/blob/master/common/lib/xmodule/xmodule/modulestore/xml_exporter.py#L339). An alternative approach would be to use globbing to ignore the specific name of the course_dir as there is only one path inside the temp directory.

┆Issue is synchronized with this [Trello card](https://trello.com/c/7vOGCAqb) by [Unito](https://www.unito.io/learn-more)

**Comment by pdpinch** [comment]
this may have been fixed upstread in edx-val 1.4.2, in PR https://github.com/edx/edx-val/pull/258

**Comment by pdpinch** [comment]
@blarghmatey tells me that this indeed was fixed in edx-val 1.4.2. I think we should close this.
