### ISSUE TITLE
Restrict account creation to specific social auth backend

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/edx-platform#148]
We would like to use the SAML authentication integration built into edX that uses the python social auth service. In order for this to function properly it means that public account creation has to be enabled. This poses a problem because we only want accounts to be created for people who have MIT accounts or Touchstone collaborator accounts. The current state of affairs is that SAML authentication and account creation is functioning, but it also means that anyone can use the standard username/password mechanism to create accounts as well.

In order for us to use the SAML integration we need a way to restrict account creation and login to specified social auth backends.

┆Issue is synchronized with this [Trello card](https://trello.com/c/5f0lsDtl) by [Unito](https://www.unito.io/learn-more)

**Comment by pdpinch** [comment]
@blarghmatey what is your proposed solution here?

Is it possible to add a django setting that specifies which social auth backends can be used for account creation?

**Comment by blarghmatey** [comment]
The desired experience is to specify a list of social auth instances as a Django setting that specifies which ones are allowed to create an account.

**Comment by blarghmatey** [comment]
This is now functional on QA next. The remaining steps are to add a feature gate for the functionality along with some tests so that we can try to get it included upstream.

**Comment by blarghmatey** [comment]
@pdpinch just wanted to check if we are planning on trying to do the extra work to make this viable for upstreaming or keep it as a cherry pick.

**Comment by pdpinch** [comment]
@blarghmatey can you or Mark make a post to https://discuss.openedx.org/ and make a proposal? 

Goal is to: 1. Find out if anyone else could use such a feature and 2. discuss and get buy in on how to do the feature flagging.

**Comment by pdpinch** [comment]
When we get around to upstreaming this, I think we need 4c6cc9a5ad and 1d8b7573e3.

**Comment by blarghmatey** [comment]
Closed by https://github.com/edx/edx-platform/pull/24789

**Comment by umarmughal824** [comment]
@blarghmatey which version of `edx-platform` is supposed to get it fixed? Should I provision the setup with `ironwood`, `juniper` or with the master branch of `mitodl/edx-platform`? I am confused about it and need clarification on it.

**Comment by blarghmatey** [comment]
The master branch will be fine for this. The intent is to get it merged in upstream so that we don't have to cherry-pick it into the Koa release once that gets created.

**Comment by umarmughal824** [comment]
@blarghmatey I am confused here that what is the scope or acceptance criteria of that issue. It has already so many merged PR's. Could you please elaborate on that? As it seems like it has already a fix PR https://github.com/edx/edx-platform/pull/24789 so what's need to be done here?

**Comment by pdpinch** [comment]
The code we have merged in our fork is working OK, but it's only been validated with the Ironwood release of edX.  Because it's only in our fork, we have to maintain it. This is risky and time-consuming. 

We want to get this feature merged upstream, into edX's master branch, so the entire edX community will be responsible for maintaining it. 

In order to get it merged into edX, we will need to:

- [x] rebase the [feature branch](https://github.com/mitodl/edx-platform/tree/third_party_only_auth) on the upstream master branch
- [x] confirm that it works
- [x] add tests
- [x] open a PR at https://www.github.com/edx/edx-platform/pulls
- [x] respond to any feedback from edX

**Comment by umarmughal824** [comment]
@pdpinch as the PR got merged, it should be closed now. So, I am closing it on this behalf.
