### ISSUE TITLE
Individual Due Date does not display in course outline 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#150]
### Steps to Reproduce

1. Configure open edX with IDDE (Individual Due Date Extension) support
2. Create a course with a problem with a due date
3. Give a learner in the course an extension
4. Navigate to the problem and confirm that it has an individual due date
5. Now, view the problem in the course outline. 

See more examples at https://github.mit.edu/mitx/Summer-2019/issues/2

### Expected Behavior

- The course outline should show the same due date as the vertical (unit) view

### Actual Behavior

- The course outline displays the original due date, not the individual due date

**Comment by asadiqbal08** [comment]
Anybody guide me over these questions: 

- what is `Individual Due Date Extension` and how to install it ?
- how to Create a `course with a problem with a due date` ? 
- How to give a learner in the course an extension ?

**Comment by pdpinch** [comment]
@asadiqbal08 take a look at this issue description: https://github.com/mitodl/salt-ops/issues/488

you can read about creating courses and setting due dates in the edX documentation at https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/developing_course/course_subsections.html#set-the-assignment-type-and-due-date-for-a-subsection

You grant the extension to a learner by going to the instructor datshboard and clicking on the extensions tab and following the directions, for example https://courses-rc.xpro.mit.edu/courses/course-v1:TestX+SysEngxB1+1T2020/instructor#view-extensions
