### ISSUE TITLE
Upstream "Fixing bug in call to query timer when structure object is empty"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#165]
Review the commit in https://github.com/mitodl/edx-platform/commit/502524ed7d8ec9c3b1e01df01c95a9813c4e7959 and submit it as a PR upstream to edx-platform master. 

### Steps to Reproduce
@blarghmatey can you help me with Steps to Reproduce here? I don't know what caused this bug. 

### Expected Behavior
* TBD

### Actual Behavior
* TBD

┆Issue is synchronized with this [Trello card](https://trello.com/c/yxHH7R2W) by [Unito](https://www.unito.io/learn-more)

**Comment by blarghmatey** [comment]
I don't recall the specific context of how I ran into this issue, but I remember it being problematic. The failure was in a component that is completely unrelated to the operation being attemtpted, but preventing normal operation of the platform. I'm sure that if I back out the change then we can find where it's causing failures.

**Comment by asadiqbal08** [comment]
Anything needs to update in **Acceptance criteria** with some more details to look around initially ?

**Comment by shaidar** [comment]
@blarghmatey How do you want to handle this as it still appears to be an issue that hasn't been addressed in `koa` or `master` upstream

**Comment by pdpinch** [comment]
As far as I know, we never encountered this in Koa. If it shows up in Lilac, we can re-open this issue.
