### ISSUE TITLE
Canvas: push assignment grades from edX to Canvas

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#166]
As an instructor using edX and Canvas (but not Stellar), I need a way to push my students' grades from edX into the Stellar gradebook. 

### Design

Follow the existing design for the remote grade book, as much as possible. 

### Proposed workflow
1. Fetch the assignment id 
1. Get a list of assignments from Canvas to see if the assignment already exists in Canvas: https://canvas.instructure.com/doc/api/assignments.html#method.assignments_api.index . The `integration_id` can be used to store edX assignments ids or names. 
1. If the assignment doesn't exist, create it: https://canvas.instructure.com/doc/api/assignments.html#method.assignments_api.create
1. Assign the grades for the assignment: https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.bulk_update

There may be some overlap with the existing remote gradebook implementation. 

### Related issues
#164 enrollments

┆Issue is synchronized with this [Trello card](https://trello.com/c/gj9F8W0e) by [Unito](https://www.unito.io/learn-more)

**Comment by gsidebo** [comment]
Closed by #172
