### ISSUE TITLE
Fix instructor dashboard JS errors

### ISSUE THREAD

**Issue by gsidebo** [mitodl/edx-platform#176]
There are several JS errors that crop up when the instructor dashboard is loaded for any course, and the periodic API call to retrieve instructor tasks appears to be failing

![](https://user-images.githubusercontent.com/14932219/91242323-1fad4500-e715-11ea-89c2-23abe4db731f.png)

The dashboard functionality still works, but this is still annoying, particularly when trying to debug broken JS functionality. Note that these errors may exist in the root repository, not just in our fork.

┆Issue is synchronized with this [Trello card](https://trello.com/c/YmkAlALC) by [Unito](https://www.unito.io/learn-more)

**Comment by pdpinch** [comment]
Does this upstream PR address any of these errors: https://github.com/edx/edx-platform/pull/24207

**Comment by gsidebo** [comment]
@pdpinch Definitely looks like it. We should incorporate that into our fork ASAP

**Comment by shaidar** [comment]
The linked PR above seems to have made it into Koa as I no longer see the constructor error when loading the instructor dashboard in the dev console. Closing for now.
