### ISSUE TITLE
Canvas: don't return 500 error when canvas ID is missing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#182]
We throw a 500 currently if the canvas ID isn't set:

See https://sentry.io/organizations/mit-office-of-digital-learning/issues/1870794109/?project=1757731&query=is%3Aunresolved+canvas&statsPeriod=14d

and https://sentry.io/organizations/mit-office-of-digital-learning/issues/1870796944/?project=1757731&query=is%3Aunresolved+canvas&statsPeriod=14d

We should just hid the canvas tab if there is no id set in the course advanced settings. 

This is a change just for mitx/lilac

**Comment by noisecapella** [comment]
What should we do instead?

**Comment by pdpinch** [comment]
I'm flexible. Whatever is the easiest (or something easier) 

- hide the Canvast tab if it isn't set
- Display a message at the top of the tab, similar to remote gradebook: 
<img width="261" alt="image" src="https://user-images.githubusercontent.com/430126/92254944-a72a4f00-ee9f-11ea-8a58-223cc018cb1f.png">
- Display an error message similar to what we display for 403 and 504s (recognizing that these are different b/c they come from canvas, not edX). 

Right now, the user sees this, which is pretty bad: 

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/430126/92255264-0ee09a00-eea0-11ea-9aa4-94afac242bc5.png">

**Comment by shaidar** [comment]
@noisecapella I vaguely remember that you already addressed this, no?

**Comment by arslanashraf7** [comment]
@pdpinch, I tried and I was unable to access the added sentry links. What could I be doing wrong, I tried to remove the `statsPeriod` from the URL though, with no luck.

**Comment by pdpinch** [comment]
I think this issue expired. Sentry has a pretty short retention period. 

I don't think this should be too hard to reproduce.

1. Enable remote grade book (might need to check in the code or with devops on how to do this)
2. Click on the Canvas tab in a course
3. Click the button to "Load Canvas Assignments" 
4. Get a messy error response
5. Set a course id in the advanced course settings in studio
6. Click the button to "Load Canvas Assignments" 
7. Get a different, less messy error response

You can check it out in my test course at https://mitx-qa-next.mitx.mit.edu/courses/course-v1:TestX+Export101+2021_Summer/instructor#view-canvas_integration

**Comment by arslanashraf7** [comment]
Closing: Associated PR had been merged but we can reopen if the issue persists.
