### ISSUE TITLE
Add indicator for deployment hash and static assets

### ISSUE THREAD

**Issue by noisecapella** [mitodl/edx-platform#184]
In other projects we add `static/hash.txt` as part of the [deployment process](https://github.com/mitodl/bootcamp-ecommerce/blob/master/bin/pre_compile#L6) for heroku, which has a commit hash of the version which is deployed. We should add something similar to our residential deployment so that we can check what version or commit hash a deployment is at in a more automated way.

Also, we should add a similar file to indicate the commit hash of the deployed version of javascript or other static assets which are part of the server, since they are sometimes not at the same version as the python code.

**Comment by pdpinch** [comment]
@noisecapella @shaidar how do we do this for Heroku apps? How can we adapt that to edX deployments?

Do you think we will be able to upstream this change?
