### ISSUE TITLE
sysadmin dashboard - phase 1: Remove "Download list of all users" functionality

### ISSUE THREAD

**Issue by briangrossman** [mitodl/edx-platform#190]
This addresses an issue in the open edX Jira: https://openedx.atlassian.net/jira/software/projects/BTR/boards/641?selectedIssue=BTR-22

---
1. Go to the Sysadmin dashboard as a staff
2. On the Users page click "Download list of all users (csv file)"

AR: 500 error appears

`TypeError at /sysadmin/`

---

<img width="547" alt="Screen Shot 2020-10-27 at 9 37 31 PM" src="https://user-images.githubusercontent.com/21342568/97380329-297e3080-189d-11eb-9a44-087759904bf1.png">

**Comment by umarmughal824** [comment]
@briangrossman On the staff and enrollment page download button is also giving the same error.

**Comment by pdpinch** [comment]
Let’s remove that too! 

> @briangrossman <https://github.com/briangrossman> On the staff and enrollment page download button is also giving the same error.

**Comment by umarmughal824** [comment]
This is what I am talking about **(Download staff and instructor list).**

![image](https://user-images.githubusercontent.com/4043989/97438917-4cfdb580-1947-11eb-9e2a-5e9da2939486.png)

**Comment by umarmughal824** [comment]
> Let’s remove that too!
> […](#)
> @briangrossman <https://github.com/briangrossman> On the staff and enrollment page download button is also giving the same error.

@pdpinch yes, I have removed it too in my PR.
