### ISSUE TITLE
sysadmin dashboard - phase 1: deprecation message

### ISSUE THREAD

**Issue by briangrossman** [mitodl/edx-platform#192]
Add a message to the UI notifying users that the sysadmin panel will be deprecated in the next release. 

Final text of the message will be determined soon. 

Message will be available on all screens of the sysadmin panel

**Comment by asadiqbal08** [comment]
@briangrossman following msg would be ok for you ?

<img width="912" alt="Screen Shot 2020-10-29 at 4 42 00 PM" src="https://user-images.githubusercontent.com/7334669/97563957-ad532c80-1a05-11eb-8291-d817ad9bffa5.png">

<img width="1208" alt="Screen Shot 2020-10-29 at 4 42 38 PM" src="https://user-images.githubusercontent.com/7334669/97564032-c3f98380-1a05-11eb-9fd5-3ed419edce09.png">

**Comment by pdpinch** [comment]
- We should be consistent about the name of this feature. It's "Sysadmin Dashboard" -- same as it is at the top of the page. 
- If it's not a link, it shouldn't be underlined. (If it is a link, let me know what it would link to)

Otherwise, this is fine.

**Comment by asadiqbal08** [comment]
PR is up https://github.com/edx/edx-platform/pull/25511
