### ISSUE TITLE
sysadmin dashboard - phase 1: deprecation warning in logs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#195]
As suggested in [OEP-21](https://open-edx-proposals.readthedocs.io/en/latest/oep-0021-proc-deprecation.html#deprecated), we should log a warning message whenever the sysadmin dashboard is accessed, e.g. 

`warnings.warn("Sysadmin Dashboard is deprecated. See DEPR-118.", DeprecationWarning)`

**Comment by pdpinch** [comment]
Just to be clear, a PR should be opened for this upstream at https://github.com/edx/edx-platform/

**Comment by arslanashraf7** [comment]
Associated upstream PR is merged. Closing this.
