### ISSUE TITLE
Rapid Response commits

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#196]
Below are all the rapid response commits in `mitx/juniper` that need be combined and submitted as one commit on the `mitx/koa` branch:
```
7c3ae42fb870dbaedd9e000667b3729eeeeed881	Refactored XBlockAside rendering and added support for student view
434a231399db22ff3e1697d209577a7c20cfee08	Adding rapid response tab to instructor dashboard
85005dceb2bc980b262c356d5efd0b7bf103667b	Replacing deprecated permissions check for rapid response instructor view
fe4469ede0ccf54b7a7fb8baf176ecd251640a19	Removing explicit unicode handling in rapid response report
97f63154e2c8a68c03a5c0b60da2dde92380928a	Fix filename for rapid response CSV exports
1bb2e219a2ec7e8de557b6b423cf5bca3d92f497	Use VIEW_DASHBOARD permission for rapid_response view (#187)
```

I believe the first commit can and should be upstreamed to edX master, but it will likely take some time to get reviewed and merged. 

### acceptance criteria

- [ ] PR merged into [mitx/koa branch](https://github.com/mitodl/edx-platform/tree/mitx/koa) for 7c3ae42fb870dbaedd9e000667b3729eeeeed881
- [ ] rebase the remaining commits into one commit
- [ ] PR merged for the remaining commits into [mitx/koa branch](https://github.com/mitodl/edx-platform/tree/mitx/koa)
- [ ] PR open upstream at edx/master for the commit 7c3ae42fb870dbaedd9e000667b3729eeeeed881

### not going to do 

- this feature isn't used by xPRO, so it doesn't need to be committed there
- the instructor dashboard features should ideally be organized into a pluggable django app, but edX doesn't have a clear path for that at this time.

**Comment by arslanashraf7** [comment]
> I believe the first commit can and should be upstreamed to edX master, but it will likely take some time to get reviewed and merged.



@shaidar As for the first point of this issue for creating upstream PR for https://github.com/mitodl/edx-platform/commit/7c3ae42fb870dbaedd9e000667b3729eeeeed881 (Refactored XBlockAside rendering and added support for student view), I believe these changes are already part of the `upstream edx-platform master` as well as our branch `mitx/koa`.

Upstream PR that got merged was: https://github.com/edx/edx-platform/pull/19089, And the commit reference is https://github.com/edx/edx-platform/commit/3dad2be55d5e406a49c92ee2f42e8ad1ad0d8a4d

Please let me know if there is something I'm missing on this?

**Comment by shaidar** [comment]
@arslanashraf7 You're right. That first commit is already in upstream and is the koa branch too so can be ignored.

**Comment by arslanashraf7** [comment]
https://github.com/mitodl/edx-platform/pull/224 PR is merged. And comments history marks the acceptance criteria. Closing this issue.
