### ISSUE TITLE
SysAdmin commits

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#197]
Below are all the SysAdmin commits in mitx/juniper that need be combined and submitted as one commit on the mitx/koa branch:
```
bdfb5cb0a659ce420ee059525a948d097abf62b7	Enhance couses page performance in system admin page (#90)
330ad116f4df7736feaae4fb5c1f7b2182c4e574	Sysadmin: Only show gitlogs for non superuser
```

### acceptance criteria

- [x] rebase all commits into one 
- [x] PR merged into [xpro/koa branch](https://github.com/mitodl/edx-platform/tree/xpro/koa)
- [x] PR merged into [mitx/koa branch](https://github.com/mitodl/edx-platform/tree/mitx/koa)

**Comment by HamzaIbnFarooq** [comment]
Sysadmin's Courses tab was giving the following error:
```
TypeError at /sysadmin/courses
'Database' object is not callable. If you meant to call the 'disconnect' method on a 'MongoClient' object it is failing because no such method exists.
```
so I had to cherry-pick 6a9995a705967c0b0234be24278b9dbbc444523f commit as well.

**Comment by HamzaIbnFarooq** [comment]
Issue solved by https://github.com/mitodl/edx-platform/pull/220 and https://github.com/mitodl/edx-platform/pull/221
