### ISSUE TITLE
Mongoengine commits

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#199]
Below are all the Mongoengine commits in mitx/juniper that need be combined and submitted as one commit on the mitx/koa branch:
```
296662075bca340d327ed85f5dc12be16635e4a9	Fixing disconnect call for mongoengine
cb68be4fc16315d21a773be34ee823c34d44a565	Remove problematic disconnect call for mongoengine in git import module
0dc9076c4186b69c2519f8fa4aa17421ae30967d	Fixing bug in call to query timer when structure object is empty
```

### acceptance criteria

- [x] evaluate whether these commits can and should be merged with #205 and #197 
- [x] rebase all commits into one 
- [x] PR merged into [xpro/koa branch](https://github.com/mitodl/edx-platform/tree/xpro/koa)
- [x] PR merged into [mitx/koa branch](https://github.com/mitodl/edx-platform/tree/mitx/koa)

**Comment by pdpinch** [comment]
@shaidar is there any reason why you separated these from the sysadmin dashboard and git log commits? As far as I know, they are all related.

**Comment by HamzaIbnFarooq** [comment]
Issue solved by https://github.com/mitodl/edx-platform/pull/220 and https://github.com/mitodl/edx-platform/pull/221
