### ISSUE TITLE
Invite Only commit

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#201]
Below is the single invite only commit in mitx/juniper that needs to be submitted on the mitx/koa branch:
```
567f1b57a4cf58ca21c45061afc968c66f7b50da	Adding INVITE_ONLY default option
```

**Comment by pdpinch** [comment]
I don't think we ever used this because the feature had unintended side effects.

**Comment by shaidar** [comment]
Closing issue

**Comment by pdpinch** [comment]
My comment _may_ have been correct about xPRO, but I think I was wrong about Residential, particularly staging.

**Comment by pdpinch** [comment]
closed by https://github.com/mitodl/edx-platform/commit/2dea5cd08115ddb0126cf7c61465649e501dbe5e
