### ISSUE TITLE
Legacy Dashboard commit

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#202]
Below is the single legacy dashboard commit in `mitx/juniper` that needs to be submitted on the `mitx/koa` branch:
```
60a6ddc7c1f24d9f7638a89c3e132b9a1a196eed	Reimplemented legacy dashboard enrollment data functionality
```

**Comment by pdpinch** [comment]
This is part of #198 Remote Gradebook. I'm adding it over there.
