### ISSUE TITLE
Submission History commit

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#203]
Below is the submission history commit in `mitx/juniper` that needs to be submitted on the `mitx/koa` branch:
```
85863bf1e30236daae104212b42ad98bfcc3fa65	Find submission history using learner's email address
```

### acceptance critiera

- [ ] confirm that this change is still needed: can you look up a user's submission history with an email address instead of a username?
- [x] PR merged into [xpro/koa branch](https://github.com/mitodl/edx-platform/tree/xpro/koa)
- [x] PR merged into [mitx/koa branch](https://github.com/mitodl/edx-platform/tree/mitx/koa)
- [ ] open a PR upstream at edx-platform/master

**Comment by pdpinch** [comment]
I actually thought this was fixed upstream some time ago, but I could be mistaken.
