### ISSUE TITLE
Individual Due Date commit

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#204]
Below is the single individual due date commit in `mitx/juniper` that needs to be submitted on the `mitx/koa` branch:
```
158d5882f1bec49bf235f02ef6c8943df9751823	Individual Due Date does not display in course outline
```

**Comment by pdpinch** [comment]
This should be tested. I suspect it has been fixed upstream already.

**Comment by shaidar** [comment]
@pdpinch How/who should follow up o this?

**Comment by pdpinch** [comment]
We never reproduced this issue in koa.
