### ISSUE TITLE
Enrollment commits

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#206]
Below are all the enrollments commits in mitx/juniper that need be combined and submitted as one commit on the mitx/koa branch:
```
76cf26b0611605ef6f601201db4eb3b7d87689d5	Adding enrollment restriction for users based on social auth providers
688db74437e3c50a31f9a8ef0a0c89abba877480	Bugfix for collaborator account access check
```

### acceptance criteria

- [x] rebase all commits into one 
- [x] PR merged into [mitx/koa branch](https://github.com/mitodl/edx-platform/tree/mitx/koa)

**Comment by pdpinch** [comment]
@blarghmatey I think this is only relevant for residential. Can you confirm?

**Comment by blarghmatey** [comment]
Yes, that is correct.
