### ISSUE TITLE
Added a configuration flag to force third party auth commit

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#208]
This has been submitted upstream but hasn't been merged yet, however we still need to merge it into our fork:
https://github.com/edx/edx-platform/pull/24789/files

### acceptance criteria

- [x] PR merged into [mitx/koa branch](https://github.com/mitodl/edx-platform/tree/mitx/koa)
- [x] PR merged into [xpro/koa branch](https://github.com/mitodl/edx-platform/tree/xpro/koa)

**Comment by umarmughal824** [comment]
As both of the PR's got merged, so closing that issue.
