### ISSUE TITLE
Added setting to manage from_email address

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#209]
This has been submitted upstream but hasn't been merged yet, however we still need to merge it into our fork:
https://github.com/edx/edx-platform/pull/24951

### acceptance criteria

- [x] PR merged into [mitx/koa branch](https://github.com/mitodl/edx-platform/tree/mitx/koa)
- [x] PR merged into [xpro/koa branch](https://github.com/mitodl/edx-platform/tree/xpro/koa)

**Comment by asadiqbal08** [comment]
Created the following PRs.
- https://github.com/mitodl/edx-platform/pull/213
- https://github.com/mitodl/edx-platform/pull/212
