### ISSUE TITLE
Canvas: Change "Submission Type" on Canvas

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#229]
Currently, when assignments are created in Canvas via the MITx-Canvas integration, the Submission Type setting in Canvas is set to Online -> File Upload. This has been causing some confusion with students, and if the default could be set to "No submission", that would be preferable. 

<img width="1422" alt="Screen Shot 2020-09-10 at 12 44 05 PM" src="https://github.mit.edu/storage/user/9183/files/202a1a80-f368-11ea-8284-9540a7a1bea3">

**Comment by pdpinch** [comment]
For context, see https://github.com/mitodl/edx-platform/issues/166

**Comment by pdpinch** [comment]
It's difficult to set up a local testing environment that integrates with Canvas. For this issue, it would be acceptable to merge reviewed but untested code, which we would then test on mitx-qa-next, which should already be configured to integrate with the Canvas test server.

**Comment by umarmughal824** [comment]
@pdpinch could I access the page that you have attached in the screenshot? I need to see the page HTML source code.

**Comment by umarmughal824** [comment]
@pdpinch it could be verified by the HTML page source so that's why I am asking if you grant me its access.

**Comment by pdpinch** [comment]
This has been deployed and confirmed on mitx-qa-next.
