### ISSUE TITLE
Show a message to user if no remote gradebook is configured in the 'remote gradebook' tab

### ISSUE THREAD

**Issue by gsidebo** [mitodl/edx-platform#24]
The 'remote gradebook' tab was added to the instructor dashboard in this PR: #21. Each course needs to specify a remote gradebook URL in advanced settings. If that value has not been set, the tab is essentially useless, so we should show the user a message that instructs them to provide a remote gradebook URL value (and, if possible, a link to the advanced course settings).

In this PR we should also look into disabling the default MIT demosite remote gradebook value for production (this was only added for ease of testing)

┆Issue is synchronized with this [Trello card](https://trello.com/c/T60T46w4) by [Unito](https://www.unito.io/learn-more)

**Comment by pdpinch** [comment]
Is this still open?

**Comment by pdpinch** [comment]
@gsidebo has this been done?

**Comment by gsidebo** [comment]
Not sure actually.... I'll look into it

**Comment by gsidebo** [comment]
No, this is still open. It would be a pretty straightforward fix

**Comment by pdpinch** [comment]
Stellar integration is on the way out, so this is moot.
