### ISSUE TITLE
Rebuild GitReload as an edX app plugin

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/edx-platform#242]
Gitreload is currently implemented as a Flask app that gets installed into the edX virtualenv. This is necessary in order for it to be able to use the edX management commands to import courses after cloning them from GitHub. The only other functionality that it provides is to act as a receiver for webhooks when new code is committed to a repository.

The current situation results in unreliable performance, and multiple locations to look at when debugging failed course imports. In order to make this more robust we should investigate integrating the functionality directly into edX via a plugin, similar to what we are doing with the Sysadmin dashboard.

### Acceptance criteria
- [ ] review https://github.com/mitodl/gitreload and identify endpoints needed for github integration
- [ ] open issue(s) in https://github.com/mitodl/edx-sysadmin/ to add the necessary endpoints 
- [ ] ensure that when a course is imported from git via the github webhook, that the import is logged to the sysadmin plugin's gitlogs

**Comment by pdpinch** [comment]
What do we need to make this work as a django plugin? The sysadmin dashboard will already need an endpoint that will import a course, given a git URL and a branch name. I suppose an integrated gitreload app would need an endpoint that can receive the webhook, but after that the import process should be the same, right?

**Comment by blarghmatey** [comment]
Correct. All that it really requires is an API endpoint that receives the webhook request and optionally validates the HMAC which can then trigger a Celery task to import the course using the existing machinery.

**Comment by pdpinch** [comment]
I added some acceptance criteria to the description based on the discussion above.

**Comment by HamzaIbnFarooq** [comment]
I have tested this gitreload feature on QA server and it seems working fine for me.
For testing, I:
  - forked demo-test-course from edx to mitodl (https://github.com/mitodl/demo-test-course)
  - added webhook to the repo
  - cloned the repo in edx-platform instance through git-import feature of sysadmin
  - pushed changes to its master branch to see if git-reload is triggered (and it got triggered)

The issue is ready to be closed from my side.

**Comment by pdpinch** [comment]
🎉 💯
