### ISSUE TITLE
SysAdmin Django application

### ISSUE THREAD

**Issue by asadiqbal08** [mitodl/edx-platform#245]
A/C

- [ ] Create a repository under mitodl
- [ ] Create a Django Application.
- [ ] Push the Django app on mitodl repository.
- [ ] Integratable Django Application with OpenEdx.

**Comment by pdpinch** [comment]
We have a [cookie-cutter template for django apps](https://github.com/mitodl/cookiecutter-djangoapp), but I don't know how suitable it is for a plugin application.

**Comment by asadiqbal08** [comment]
@pdpinch anyone have plan to create a private repository over https://github.com/mitodl ? i.e. SysAdmin

**Comment by HamzaIbnFarooq** [comment]
@asadiqbal08 I have already created a public repo at https://github.com/mitodl/edx-sysadmin and I think it wasn't meant to be private.

**Comment by pdpinch** [comment]
Yes, it should be public.

**Comment by HamzaIbnFarooq** [comment]
The [cookie cutter](https://github.com/mitodl/cookiecutter-djangoapp) doesn't seem to be suitable for our plugin. That's only suitable for applications like xpro, micromasters and bootcamps, not for plugins.

**Comment by HamzaIbnFarooq** [comment]
FYI: I have used [edX's cookiecutter](https://github.com/edx/edx-cookiecutters) and configured GitHub Actions instead of Travis.

**Comment by HamzaIbnFarooq** [comment]
Closed by https://github.com/mitodl/edx-sysadmin/pull/5 and https://github.com/mitodl/edx-sysadmin/pull/6
