### ISSUE TITLE
Unicode in loncapa (python) scripts raises an exception in ficus

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#25]
Courseware that contains python with unicode throws an error in Studio and lms. This used to work fine in dogwood, but was apparently broken in 

edX JIRA ticket [CRI-66](https://openedx.atlassian.net/browse/CRI-66) has a good test case and a solution for this. I don't know why the fix was never merged. 

This is causing problems for MITx Residential, and we'd like to fix it asap. After that, we should open a PR upstream in edx-platform.

**Comment by pdpinch** [comment]
In the mitodl branch, the line that needs to be changed is https://github.com/mitodl/edx-platform/blob/master/common/lib/xmodule/xmodule/capa_base.py#L703

**Comment by blarghmatey** [comment]
This has been fixed and deployed.
