### ISSUE TITLE
[SysAdmin] Remove the SysAdmin from OpenEdx

### ISSUE THREAD

**Issue by asadiqbal08** [mitodl/edx-platform#250]
After the application is stable to handle all the functionality. 

- [ ] Need to remove all the SysAdmin logic from OpenEdx (PR to OpenEdx)

**Comment by HamzaIbnFarooq** [comment]
@pdpinch 
Sysadmin has a command for git course import (https://github.com/edx/edx-platform/blob/master/lms/djangoapps/dashboard/management/commands/git_add_course.py) which is quite dependent on the stuff which we have moved to our plugin, so I have to remove that command from edx-platform.

If we need that command then we have to add it into our plugin, which is not mentioned under the scope of edx-sysadmin plugin so far. So if we need to get that command moved as well please create a ticket for that.

**Comment by pdpinch** [comment]
Thanks for catching this. Please open another issue in the sysadmin plugin repo to add the management command.

**Comment by HamzaIbnFarooq** [comment]
> Please open another issue in the sysadmin plugin repo to add the management command.

Opened issue: https://github.com/mitodl/edx-sysadmin/issues/15

**Comment by pdpinch** [comment]
now that https://github.com/edx/edx-platform/pull/27213 has merged, I think we can close this.

**Comment by HamzaIbnFarooq** [comment]
Closed by https://github.com/edx/edx-platform/pull/27213
