### ISSUE TITLE
Lilac: Remote gradebook & Canvas cherry-picks

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#255]
The Remote Gradebook and Canvas features on Residential MITx are both Instructor dashboard features that push grades from edX to remote services. They share much of the same code, so it seems to make sense to combine them. 

Cherry-pick the following commits into one commit and test that it works on the mitx/lilac branch. 

(most recent at the top)
608828d218b85d3e901a71016e76e5c3c464c659
e6303763d849a8a164659082627962ab62bd916b
e52d609c0059d360d9794ce613146df1907929f2
b3317783973d139ec894f0aa3859aa7069f5385d
697ce492e3c351f2c98c0673483e8a8fd798e0af
1374507ede574a519f01c3bdee8a28dd22d2d357
63ceb85a9e95c340f62097452958c88117d31ece
ca3a1a63035fbe8b3e4409ab05c0a6dc24516fd6

**Comment by pdpinch** [comment]
This PR should be opened against the mitx/lilac branch.

**Comment by umarmughal824** [comment]
@pdpinch @blarghmatey have we deployed `lilac` on our Mitx test server for the sake of testing?

**Comment by pdpinch** [comment]
We're working on deploying it now, but it's going to take some time. Ideally we would have these cherry picks ready for the deployment.
