### ISSUE TITLE
Relative path routing support for library authoring MFE

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/edx-platform#295]
In order to support the Blockstore plugin functionality for edx-platform we will need to be able to deploy the library authoring MFE (https://github.com/openedx/frontend-app-library-authoring). That MFE does not currently support path-based routing, which forces us to use a dedicated subdomain to run it. We would like to update the code to include support for path-based routing in the same manner as frontend-app-learning, frontend-app-gradebook, etc.

**Comment by pdpinch** [comment]
@asadiqbal08 I think you did similar work on https://github.com/openedx/frontend-component-header 

@blarghmatey just for an example, can you tell us what route you would want to use for this MFE?

**Comment by blarghmatey** [comment]
The route will be managed by the env variables during the build, but for sake of argument we'll likely put it at `/authoring`

**Comment by asadiqbal08** [comment]
@blarghmatey for a quick refresh, Can you please reference the `frontend-app-learning` that working in the desired manner ? and in the `authoring MFE` what actually are you expecting to change ?

**Comment by blarghmatey** [comment]
So, [this](https://github.com/openedx/frontend-app-learning) is the learning MFE that we use which has the relative path functionality available to it. For the authoring MFE we would like to be able to deploy it so that it will expect to load at a particular route on the domain where it's deployed. As it currently exists it expects that all interactions with it will happen at the root path (`/`) of an arbitrary domain. This boils down to a setting in the React router which should be handled in the [`frontend-platform`](https://github.com/openedx/frontend-platform) repository, but I believe there's some wiring in the authoring MFE that needs to be included to take advantage of that.

**Comment by asadiqbal08** [comment]
@pdpinch @blarghmatey After installing the `library-authoring-mfe`, Checking out its routing paths and after reading out some previous discussion over this [thread](https://github.com/mitodl/mitxonline/issues/42). I think we might not need any specific change in this MFE and we just be able to use the `public_path` as we are doing for learning MFE. 

I am able to run the MFE after getting pull of this repo and did this locally.

- Set `PUBLIC_PATH` variable to `/authoring` in .env.development — This will be set in .env in the production
- Restart the `frontend-app-library-authoring` container to reload the above change e.g. — `make dev.restart-container.frontend-app-library-authoring`

Now, I am able to load the pages on the following routes. 

```
http://localhost:3001/authoring/library/lib:uetX:CSPROB
```
![screencapture-localhost-3001-authoring-library-lib-uetX-CSPROB-2022-04-11-16_40_19](https://user-images.githubusercontent.com/7334669/162732158-0fa38edd-2613-4768-a7bd-7dfdeb3df4d1.png)

- The version of frontend-platform was updated in this [PR](https://github.com/openedx/frontend-app-library-authoring/commit/b95c198b5b5b2ca7520ff048c5bffd1ff6c9ab05) (27 days ago)
- The version of frontend-build was updated in this [PR](https://github.com/openedx/frontend-app-library-authoring/commit/f82fbdfc55f4fc0148a96b1fc7520bfd6fb0fb1c) (few days back)

Let me know, If we are good with this approach ?
