### ISSUE TITLE
Canvas Integration: Refactor the cherry-pick commit as per the canvas plugin migration (Nutmeg)

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/edx-platform#296]
### Description

In our initial development of the [Canvas Integration Plugin](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_canvas_integration) we refactored a major part of the commits into a plugin itself. There were a few things that we couldn't convert to the plugin either because of the lack of edx-platform support or some complex customization.

One part of the refactored commit was the static assets which we couldn't serve through the plugin and kept in [the counterpart cherry-pick](https://github.com/mitodl/edx-platform/pull/274/commits/97a51d208f3cdfd26df0a62281b0964de10ff40a).

### What to do?

With the Nutmeg release, now the platform supports serving the static content (html/JS) right from the plugin. So we need to refactor the [the counterpart cherry-pick](https://github.com/mitodl/edx-platform/pull/274/commits/97a51d208f3cdfd26df0a62281b0964de10ff40a) and remove the code that is being migrated to the plugin in https://github.com/mitodl/open-edx-plugins/pull/54.

The PR should be created against the `mitodl/nutmeg` branch.

**Comment by arslanashraf7** [comment]
@blarghmatey With the new Nutmeg migrations for our two plugins [ol-openedx-rapid-response-reports](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_rapid_response_reports) and [ol-openedx-canvas-integration](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_canvas_integration) there will be changes in cherry-picks for [mitx/nutmeg](https://github.com/mitodl/edx-platform/tree/mitx/nutmeg).

The related PRs are at:
- For canvas Integration https://github.com/mitodl/open-edx-plugins/pull/54
- For rapid response reports https://github.com/mitodl/open-edx-plugins/pull/51

**For Posterity**

Looks like we have already cherry-picked the commits in our `mitx/nutmeg` branch but after the migration PRs are merged:
-  For `ol-openedx-rapid-response-reports` plugin we won't need to cherry-pick any commits anymore (So we have to remove that cherry-pick from `mitx/nutmeg`)
- For `ol-openedx-canvas-integration` we will need to review https://github.com/mitodl/edx-platform/pull/297 and merge this into `mitx/maple` instead of the old cherry-pick which still has the assets in it.

Let me know what you think on that.

**Comment by pdpinch** [comment]
I'm pretty sure we can close this.
