### ISSUE TITLE
Update canvas grades integration to work with Palm release

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#305]
In the Olive release of Residential MITx, we include one commit that provides Instructor Dashboard access to the feature to push grades from open edX to Canvas. 

1. Review this commit and see if it still works in palm.master
2. Is there some way we can migrate this functionality out of edx-platform? Ideally it would be added to https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_canvas_integration 
3. If it can't be moved into a separate repository, update it so it will continue to work with Palm

**Comment by blarghmatey** [comment]
I have cherry-picked the commit from our `mitx/olive` branch into a `mitx/palm` branch that was created from `open-release/palm.master`. This will be included in the build once we deploy this release to residential CI

**Comment by pdpinch** [comment]
This didn't come up in testing palm in Residential, so I'm going to assume it can be closed.
