### ISSUE TITLE
Make xqueue post back URL configurable

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#42]
xqueue uses the `sitename` setting as the post back URL for returning grades. This setting is also used for user-facing interfaces in Studio. As a DevOps, I'd like to have these settings be isolated so I can choose a post back URL that doesn't interfere with user-facing interfaces.

**Comment by gsidebo** [comment]
@blarghmatey I think this might already be configurable: https://github.com/mitodl/edx-platform/blob/mitx/ficus-4rc1/lms/djangoapps/courseware/module_render.py#L335. If the `XQUEUE_INTERFACE` setting (dict) has a value for `callback_url`, I can confirm locally that the `lms_callback_url` value in XQueue begins with that setting value when you submit a problem. That `lms_callback_url` value is what XQueue uses to post the grade back to LMS (https://github.com/edx/xqueue/blob/master/queue/consumer.py#L139). Is that setting not sufficient for what you need to do?
