### ISSUE TITLE
Performance: /sysadmin/courses is too slow

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#44]
It can take several minutes to load the page /sysadmin/courses which combines a form to load/delete courses with a status update on all courses. This is particularly bad on the staging server due to the number of courses. 

I believe a contributing factor here is that the page is checking the commit hash for every course repo on disk before returning, which can take a long time.

**Comment by pdpinch** [comment]
@gsidebo and @blarghmatey can you guys coordinate on this?

I feel like our current situation is an ops issue, but in the long run we need to optimize how this page is constructed.

**Comment by pdpinch** [comment]
After a brief discussion with @blarghmatey and @gsidebo I think the quickest approach is to just cache the results of the page for, say, five minutes. That way when the page load times out, users should be able to simply reload the page and get the cached version. 

If we do this we need a way (perhaps a query parameter like `?no-cache`) to allow the user to force the cache to flush.

**Comment by amir-qayyum-khan** [comment]
@pdpinch 
Sysadmin This pulls out some git info like the last commit. please see

- https://github.com/edx/edx-platform/blob/master/lms/djangoapps/dashboard/sysadmin.py#L449
- https://github.com/edx/edx-platform/blob/master/lms/djangoapps/dashboard/sysadmin.py#L432
- https://github.com/edx/edx-platform/blob/master/lms/djangoapps/dashboard/sysadmin.py#L339

this can be case of slow loading. We are showing git commit in out table. Do we need to show it.

- Should we remove `Git Commit , Last Change, Date`  altogether? it is the latest commit on course. We can see the commit on `git logs` tab?
-  Should we add cache to save this info for some time? And may be in background/celery update cache?
- Is there any other solution that comes in your mind?

<img width="1219" alt="screen shot 2018-05-21 at 8 56 56 pm" src="https://user-images.githubusercontent.com/10431250/40317005-87f2e2d6-5d39-11e8-95ed-06249ad055a2.png">

**Comment by pdpinch** [comment]
Last change and last editor are definitely helpful and difficult to look up otherwise. 

In earlier discussions, we were leaning towards some sort of caching. It seems to me that this only needs to be updated when a course is imported through git. Can we leverage the git log table?

**Comment by amir-qayyum-khan** [comment]
@pdpinch Should i load git log for new imports from `CourseImportLog` mongo table and for old course from git?

**Comment by pdpinch** [comment]
I think if there isn't an entry in git log, we can just skip it and leave the Git Commit , Last Change, Date fields empty.

**Comment by amir-qayyum-khan** [comment]
this is what i am doing i code.

**Comment by amir-qayyum-khan** [comment]
are you saying to use gitimportlog table? just skip enteries without git
logs?

my code skips enteries with git log and the save logs data in gitimportlog
table.

**Comment by amir-qayyum-khan** [comment]
close via #90

**Comment by pdpinch** [comment]
This looks to me like this has been deployed to QA (See https://mitx-qa-next.mitx.mit.edu/sysadmin/courses). 

@amir-qayyum-khan Can you confirm?

I'd like to get this upstreamed to edX.

**Comment by blarghmatey** [comment]
Yes, this has been deployed.

**Comment by amir-qayyum-khan** [comment]
Sorry i cant confirm, because i did not saw the time on qa at first place. currently it is taking 10s to load courses, anyone know what was it taking before?
