### ISSUE TITLE
Exceptions raised in jailed code are getting escaped excessively

### ISSUE THREAD

**Issue by jolyonb** [mitodl/edx-platform#55]
Here is an MWE of code that generates an error message that is being excessively escaped. Put this in a problem.

````
<problem>
<script type="loncapa/python">
def grader(expect, answer):
    raise Exception("This shouldn't be escaped!")
</script>

  <p>Press submit! (Enter anything)</p>
  <customresponse cfn="grader">
    <textline />
  </customresponse>
</problem>
````

**Comment by pdpinch** [comment]
I opened https://github.com/edx/edx-platform/pull/17369 at edX

**Comment by pdpinch** [comment]
@mitodl/devops not urgent, but it would be nice if we could cherry-pick https://github.com/edx/edx-platform/commit/a7c09be6f0335a2cd0c44c59c5e9f6f3dee91283 into our ginkgo fork.

**Comment by pdpinch** [comment]
This has been picked and deployed.
