### ISSUE TITLE
Hawthorn: Revert "Fixed Aberrant Button on LMS Course About Page"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#68]
this button is no more in Gingko, I think we need to remove this css. Mitx/ginkgo is still using older css, that's why it has button,

- see [ficus code](https://github.com/edx/edx-platform/blob/open-release/ficus.master/lms/templates/courseware/course_about.html#L118)
- see [edx master code](https://github.com/edx/edx-platform/blob/master/lms/templates/courseware/course_about.html#L120)

When we start working on a Hawthorn theme, we should revert the changes made in https://github.com/mitodl/mitx-theme/commit/74c314234d936d1422e12a5b4ba3741f497ab2df

**Comment by amir-qayyum-khan** [comment]
@pdpinch this button is no more in Gingko, I think we need to remove this css. Mitx/ginkgo is still using older css, thats why it has button, 
we also need to update mitx-theme for edx master

- see [ficus code](https://github.com/edx/edx-platform/blob/open-release/ficus.master/lms/templates/courseware/course_about.html#L118)
- see [edx master code](https://github.com/edx/edx-platform/blob/master/lms/templates/courseware/course_about.html#L120)

**Comment by pdpinch** [comment]
Thanks @amir-qayyum-khan 

I'm going to move this to the theme repo.

**Comment by pdpinch** [comment]
Issue moved to [mitodl/mitx-theme #55](https://github.com/mitodl/mitx-theme/issues/55) via [**ZenHub**](https://www.zenhub.com/)
