### ISSUE TITLE
Upstream: add Sysadmin panel link to template

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#69]
This might be a long shot, but since the sysadmin panel is in master, I don't see why the link to it shouldn't be in master as well. Getting this into master would reduce our need to maintain the template in our theme. 

See https://github.com/mitodl/mitx-theme/commit/e6cf4ee3588f64e5534e12b956c189007d51dd81

**Comment by pdpinch** [comment]
@annagav were you able to determine whether this is still necessary?

**Comment by annagav** [comment]
For that old mitx-theme PR the template that was being modified is now equivalent to this template https://github.com/edx/edx-platform/blob/master/lms/templates/header/navbar-authenticated.html#L47
