### ISSUE TITLE
Upstream: Fix unthemed error pages

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#72]
This fix to Open edX theming should be valuable to all Open edX users. 

Open #67 against the master branch of edx/edx-platform

**Comment by gsidebo** [comment]
@pdpinch FYI: https://github.com/edx/edx-platform/pull/17446. This includes the LMS fix too (it was very cheap)

**Comment by pdpinch** [comment]
This was merged upstream.
