### ISSUE TITLE
Upstream: restore remote gradebook functionality in Open edX

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#74]
In Ficus and Ginkgo, we've done a lot of work to restore the functionality of the remote gradebook that was first deprecated in the Dogwood release of open edX. 

To help maintain this feature, we should merge it back into master. The changes we made should make it more compatible with current edX approaches. We:

* move the UI from the legacy dashboard to the current instructor dashboard
* made it work with split-mongo 
* used the grades API to fetch grades
* set up the sometimes-slow grade export process to run as asynchronous instructor task. 

All told, our work on the remote gradebook includes the following commits:

2664166 Reimplemented legacy remote gradebook grade export functionality
3905210 Reimplemented legacy dashboard enrollment data functionality

439e37c Reimplemented remote gradebook merge/overload functionality

c3d8fda Ficus: Allowed creation of multiple tasks for RGB (#45)
7119beb Rgb commits cherry picked from MY PRS (#58)
5cad73c Fixed remote geade book gingko issue (#61)
f2d9eba Fixed circular import for remote gradebook functionality

0667bc1 Merge pull request #63 from mitodl/tmacey/mitx/ginkgo/gradebook_circu

09fc958 Fixed RGB task message (#81)

┆Issue is synchronized with this [Trello card](https://trello.com/c/GQwxUhTW) by [Unito](https://www.unito.io/learn-more)

**Comment by amir-qayyum-khan** [comment]
is this complete list f commit, or i need to look into repo for anything missing

@pdpinch @blarghmatey

**Comment by pdpinch** [comment]
Gavin's taken this over to make it follow the edX application plugin pattern, like https://github.com/edx/edx-platform/pull/17385

**Comment by pdpinch** [comment]
Well, that was overly optimistic. We do need to turn this into a pluggable app, but it won't happen in 2018.

**Comment by pdpinch** [comment]
The stellar integration is moot at this point, so I'm going to close this. If we pursue something like this, it will be for Canvas integration.
