### ISSUE TITLE
Staff Debug doesn't work with usernames with an `@` in them

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#76]
- The Staff Debug button, which typically takes a username, results in a failure message when the touchstone username is entered. 
![screenshot 2017-12-15 15 04 17](https://github.mit.edu/storage/user/9183/files/6a824e64-e1a9-11e7-87e8-e1ed233a5ea2)

- Using the touchstone account's email address in the Staff Debug button results in a success message, but there is no change to the student's state. 
![screenshot 2017-12-15 15 08 53](https://github.mit.edu/storage/user/9183/files/00e586c8-e1aa-11e7-9506-f41c6ac7d45c)

Presumably, this can be fixed similarly to https://github.com/mitodl/edx-platform/pull/70

**Comment by pdpinch** [comment]
@amir-qayyum-khan just to be clear: this should be an upstream PR

**Comment by amir-qayyum-khan** [comment]
@pdpinch i create a user with `@` in its name,
i am not able to enroll it `instructor#view-membership`, Do you get same error here
Is there any env settings to allow @ in username at resedentials?

<img width="1018" alt="screen shot 2018-02-27 at 5 58 10 pm" src="https://user-images.githubusercontent.com/10431250/36730026-d67d1248-1be7-11e8-8d9e-637cbfc049ec.png">

**Comment by pdpinch** [comment]
Sorry, I thought I mentioned this in the related issues: you have to allow unicode usernames to be able to use an @ sign in the username. 

See https://github.com/mitodl/salt-ops/blob/master/pillar/edx/mitx-qa.sls#L23

**Comment by pdpinch** [comment]
Congratulations @amir-qayyum-khan on getting this merged. 

@mitodl/devops this means that https://github.com/edx/edx-platform/commit/663dc1af8f175e1872156266811ea79f0e740381 should be cherry-picked instead of 666baa8c455c99aeede8a70a59230d240806de39

I don't think we need to rush to change this but if/when we take another cut from master, we'll want to omit 666baa8c455c99aeede8a70a59230d240806de39
