### ISSUE TITLE
Upstream: Fixed bug involving users that could not be found using 'view this course as' functionality

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#77]
open PR #70 upstream (2d13be0)

**Comment by pdpinch** [comment]
@amir-qayyum-khan what's the status of this?

**Comment by amir-qayyum-khan** [comment]
@pdpinch PR is already opened with addition of tests https://github.com/edx/edx-platform/pull/17634/

**Comment by pdpinch** [comment]
edX has merged this
