### ISSUE TITLE
export to git with every course publish event

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#8]
As a course author, I'd like to preserve a version of my course every time I publish it. 

This can be accomplished by executing a [git export](https://github.com/mitodl/edx-platform/blob/master/cms/djangoapps/contentstore/git_export_utils.py) whenever a `course_published` signal is sent. "git export" exports the course to a local directory and then runs a git push to a remote repository specified in the course's advanced setting. 

If the course author needs to revert a change, they can save from git and import the course. Or an admin can do a "git import" from the sysadmin panel.

**Comment by gsidebo** [comment]
@pdpinch Seems sensible to put this behind a new feature flag, a la `ENABLE_GIT_AUTO_EXPORT`. If you agree, let me know if you think it should be on or off by default

**Comment by pdpinch** [comment]
Feature flag would be great. 

Should default to off

**Comment by pdpinch** [comment]
@blarghmatey I think we can close this now? #13 and #49 baked into the AMI, right?

**Comment by blarghmatey** [comment]
Yes, that is correct.
