### ISSUE TITLE
Assigning an individual due date extension changes course outline for all learners

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#82]
but doesn't actually apply the extension to the problem. Learners cannot submit a response to the problem that was changed. 

See https://odl.zendesk.com/agent/tickets/15664

The issue manifests on [mitx-qa.mitx.mit.edu](https://mitx-qa.mitx.mit.edu/courses/course-v1:TestX+Ginkgo101+course/courseware/2b68edde68994e7e83884e7f9abce12d/e9b6daed541542fc90f315c18cc173b2/?activate_block_id=block-v1%3ATestX%2BGinkgo101%2Bcourse%2Btype%40sequential%2Bblock%40e9b6daed541542fc90f315c18cc173b2) and also lms.mitx.mit.edu

**Comment by pdpinch** [comment]
FYI @NotoriousMKD @amir-qayyum-khan

**Comment by pdpinch** [comment]
This should be working now on Residential MITx, although edX still hasn't merged the PR upstream. 

Once this is confirmed working on Residential MITx, I'll remove it from the Hawthorn epic. 

I'll leave the issue open until edX merges it.

**Comment by pdpinch** [comment]
@amir-qayyum-khan this was merged upstream at edX, right?

**Comment by amir-qayyum-khan** [comment]
yes @pdpinch.
