### ISSUE TITLE
Upstream "export to git with every course publish event"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#87]
Although edX is unlikely to accept this feature as it is currently implemented, it would still be helpful for us to have a a single PR/commit that is rebased and can be cherry-picked into our Residential MITx Hawthorn release. 

It should include the following commits:
- [x] e0bb7e4
- [x] c9accc4
- [x] e03a492
- [x] 58b122a

**Comment by pdpinch** [comment]
FYI @mitodl/devops

**Comment by amir-qayyum-khan** [comment]
@mitodl/devops already picked these commits into mitx/hawthorn. i just added tests and fixed pylint issues

**Comment by pdpinch** [comment]
@amir-qayyum-khan can this code be written as a pluggable django application, so we can manage it in its own repository instead of merging it into edx-platform?

**Comment by amir-qayyum-khan** [comment]
sure, i will look into this.

**Comment by pdpinch** [comment]
This is not in progress, as far as I know. I'm moving it back to the backlog.

**Comment by amir-qayyum-khan** [comment]
Made a repo https://github.com/mitodl/edx-git-auto-export and added all code related git export there.

**Comment by pdpinch** [comment]
Closing this in favor of the new app
